<a href="https://colab.research.google.com/github/aakshataaa/Airline-Dashboard/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a python package, it stands fr nmerical python
It is a library consisting of  multidimensional array objects and the collection of routines for processing of array.


Why numpy?
1.faster calculations
2.Memory efficient
3.Supports multi dimensional arrays

Key Features:
1. ndarray: N-dimensional array for numerical data
2. Vectorization: Perform operations on entire arrays(no need for explicit loops)
3. Mathematical Tools: Built in functions for:
     a.Statistics
     b.Linear Algebra
     c.Aggregations
4. High Performance: Optimized using C under the hood
5. Shape & Reshaping: Easily change array dimension

Numpy is the foundation for Data Science & ML.


In [1]:
import numpy as np
print(np.__version__)

2.0.2


Array:
An array stores multiple values in a singl structure.
Element are usually of the same data type
Each element has a position(index)

Characteristics:
Homogenous: same type of data
Ordered: Elements have fixed positions
Efficient Access: Quick retrieval using index

In [3]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


1D Array:
It is a simple list of elements, similar to a traditional Python list

2D Array:
Represents a table or matrix, with rows and columns.Each element
occupies a specific position.

In [9]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

3D Array:
Adds a third dimension to the table , often representing a cube or a volume of data


in output it will come like if we want to find shape (1,4,3) it says 1 layer,4 rows in each layer,3 columns.

In [10]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr3)
arr3.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


(1, 4, 3)

Indexing:
Array indexing means accessing a specific element(value) from an array using its position number(index)

Slicing:
Array Slicing is the process of extracting multiple elements from an array using a range of indicies.


In [14]:
print(arr[2]) #indexing
print(arr[1:4]) #slicing
print(arr[1:])
print(arr[:4])
print(arr[::-1]) #reverse

3
[2 3 4]
[2 3 4]
[1 2 3 4]
[4 3 2 1]
